name: repository dispatch reception
on:
  repository_dispatch:
    types: [build_dispatch]
jobs:
  build_dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: ${{ secrets.USER_NAME }}/${{ secrets.FRONTEND_REPO }} 
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          path: frontend
      - name: install packages on frontend
        run: |
          cd frontend
          npm install
      - name: create build files on frontend
        run: |
          cd frontend
          npm run build
      - name: replace build files in backend and commit changes
        run: |
          rm -r public/build
          mv frontend/build public
          git config --global user.name ${{ secrets.USER_NAME }}
          git config --global user.email ${{ secrets.USER_EMAIL }}
          git config --global user.password ${{ secrets.GITHUB_TOKEN }}
          git status
          git add .
          git commit -m "Update React build files from dispatch event originating from frontend push."
          git push origin master
